import Questionario from '../components/Questionario';

interface Pergunta {
  pergunta: string;
  respostasErradas: string[];
  respostaCorreta: string;
  mensagensErradas: Record<string, string>;
}

interface PerguntaComMensagem extends Pergunta {
  mensagem: string;
}

function Penal() {
  const perguntas: PerguntaComMensagem[] = [
    {
      pergunta: "A administração pública pode estar sujeita tanto ao regime jurídico de direito privado quanto ao regime jurídico de direito público. ",
      respostasErradas: ["Falso"],
      respostaCorreta: "Verdadeiro",
      mensagem: "[CORRETA]  A diferenciação entre o regime de direito público e o regime de direito privado é um trabalho doutrinário, porém difícil de se observar no mundo real. Por exemplo, no âmbito da Administração Pública, as relações jurídicas ora são regidas pelo direito público ora pelo direito privado. Cita-se, por exemplo, a realização de concurso público (direito público) e um contrato de financiamento (direito privado) realizados por uma empresa pública", mensagensErradas: {
        "Falso": "A diferenciação entre o regime de direito público e o regime de direito privado é um trabalho doutrinário, porém difícil de se observar no mundo real. Por exemplo, no âmbito da Administração Pública, as relações jurídicas ora são regidas pelo direito público ora pelo direito privado. Cita-se, por exemplo, a realização de concurso público (direito público) e um contrato de financiamento (direito privado) realizados por uma empresa pública",
      },
    },

    {
      pergunta: "No que diz respeito a consumação e tentativa, corresponde a uma das etapas da fase interna ou mental:",
      respostasErradas: ["manifestação", "preparação", "execução", "consumação"],
      respostaCorreta: "Resolução",
      mensagem: "[CORRETA]  O iter criminis possui duas fases: fase interna, formada pela cogitação e fase externa, formada pela preparação, pela execução e pela consumação. Como a preparação, a execução e a consumação são etapas da fase externa, ou seja, quando já há exteriorização do fato, estão erradas as alternativas B, D e E. A manifestação sequer é trabalhada por muitos doutrinadores, e seria uma fase entre a cogitação e a preparação, consistente no ato de manifestar a terceiros o intento de praticar o crime. Por fim, chegamos à cogitação. A cogitação é a fase mental ou interna, ou seja, a etapa em que o agente está pensando acerca da prática, ou não, do crime. Pode ser dividida em: a) idealização (ter a ideia criminosa); b) deliberação (ato de deliberar mentalmente sobre a conveniência, ou não, de praticar o delito; e c) resolução (momento em que o agente, mentalmente, decide que irá praticar o delito). Logo, vemos que a resolução é a última etapa da cogitação, sendo, portanto, integrante da fase interna do iter criminis.",
      mensagensErradas: {
        "manifestação": " O iter criminis possui duas fases: fase interna, formada pela cogitação e fase externa, formada pela preparação, pela execução e pela consumação. Como a preparação, a execução e a consumação são etapas da fase externa, ou seja, quando já há exteriorização do fato, estão erradas as alternativas B, D e E. A manifestação sequer é trabalhada por muitos doutrinadores, e seria uma fase entre a cogitação e a preparação, consistente no ato de manifestar a terceiros o intento de praticar o crime. Por fim, chegamos à cogitação. A cogitação é a fase mental ou interna, ou seja, a etapa em que o agente está pensando acerca da prática, ou não, do crime. Pode ser dividida em: a) idealização (ter a ideia criminosa); b) deliberação (ato de deliberar mentalmente sobre a conveniência, ou não, de praticar o delito; e c) resolução (momento em que o agente, mentalmente, decide que irá praticar o delito). Logo, vemos que a resolução é a última etapa da cogitação, sendo, portanto, integrante da fase interna do iter criminis.",
        "preparação": "O iter criminis possui duas fases: fase interna, formada pela cogitação e fase externa, formada pela preparação, pela execução e pela consumação. Como a preparação, a execução e a consumação são etapas da fase externa, ou seja, quando já há exteriorização do fato, estão erradas as alternativas B, D e E. A manifestação sequer é trabalhada por muitos doutrinadores, e seria uma fase entre a cogitação e a preparação, consistente no ato de manifestar a terceiros o intento de praticar o crime. Por fim, chegamos à cogitação. A cogitação é a fase mental ou interna, ou seja, a etapa em que o agente está pensando acerca da prática, ou não, do crime. Pode ser dividida em: a) idealização (ter a ideia criminosa); b) deliberação (ato de deliberar mentalmente sobre a conveniência, ou não, de praticar o delito; e c) resolução (momento em que o agente, mentalmente, decide que irá praticar o delito). Logo, vemos que a resolução é a última etapa da cogitação, sendo, portanto, integrante da fase interna do iter criminis.",
        "execução": " O iter criminis possui duas fases: fase interna, formada pela cogitação e fase externa, formada pela preparação, pela execução e pela consumação. Como a preparação, a execução e a consumação são etapas da fase externa, ou seja, quando já há exteriorização do fato, estão erradas as alternativas B, D e E. A manifestação sequer é trabalhada por muitos doutrinadores, e seria uma fase entre a cogitação e a preparação, consistente no ato de manifestar a terceiros o intento de praticar o crime. Por fim, chegamos à cogitação. A cogitação é a fase mental ou interna, ou seja, a etapa em que o agente está pensando acerca da prática, ou não, do crime. Pode ser dividida em: a) idealização (ter a ideia criminosa); b) deliberação (ato de deliberar mentalmente sobre a conveniência, ou não, de praticar o delito; e c) resolução (momento em que o agente, mentalmente, decide que irá praticar o delito). Logo, vemos que a resolução é a última etapa da cogitação, sendo, portanto, integrante da fase interna do iter criminis. ",
        "consumação": "O iter criminis possui duas fases: fase interna, formada pela cogitação e fase externa, formada pela preparação, pela execução e pela consumação. Como a preparação, a execução e a consumação são etapas da fase externa, ou seja, quando já há exteriorização do fato, estão erradas as alternativas B, D e E. A manifestação sequer é trabalhada por muitos doutrinadores, e seria uma fase entre a cogitação e a preparação, consistente no ato de manifestar a terceiros o intento de praticar o crime. Por fim, chegamos à cogitação. A cogitação é a fase mental ou interna, ou seja, a etapa em que o agente está pensando acerca da prática, ou não, do crime. Pode ser dividida em: a) idealização (ter a ideia criminosa); b) deliberação (ato de deliberar mentalmente sobre a conveniência, ou não, de praticar o delito; e c) resolução (momento em que o agente, mentalmente, decide que irá praticar o delito). Logo, vemos que a resolução é a última etapa da cogitação, sendo, portanto, integrante da fase interna do iter criminis.",
      },
    },

    {
      pergunta: "Cássio, com a intenção de matar Patrício, efetua disparo de arma de fogo em sua direção, que atinge seu braço e o faz cair no chão. Enquanto caminha na direção de Patrício para efetuar novo disparo, Cássio percebe a aproximação de policiais e se evade do local, deixando Patrício apenas com o ferimento no braço.",
      respostasErradas: ["tentativa de homicídio, com diminuição da pena pela desistência voluntária", "lesão corporal, pois houve desistência voluntária", "tentativa de homicídio, com diminuição da pena pelo arrependimento eficaz", "lesão corporal, pois houve arrependimento eficaz"],
      respostaCorreta: "tentativa de homicídio",
      mensagem: "[CORRETA]  Nesse caso houve homicídio na forma tentada. Não há que se falar em desistência voluntária, uma vez que a desistência do agente se deu em razão de uma influência externa coativa (a chegada da polícia). Logo, Cássio não desistiu porque quis, mas porque se viu obrigado a isso. Assim, podemos dizer que foi iniciada a execução, mas a consumação não ocorreu por circunstâncias alheias à vontade do agente, logo, tentativa (art. 14, II do CP).",
      mensagensErradas: {
        "tentativa de homicídio, com diminuição da pena pela desistência voluntária": " Nesse caso houve homicídio na forma tentada. Não há que se falar em desistência voluntária, uma vez que a desistência do agente se deu em razão de uma influência externa coativa (a chegada da polícia). Logo, Cássio não desistiu porque quis, mas porque se viu obrigado a isso. Assim, podemos dizer que foi iniciada a execução, mas a consumação não ocorreu por circunstâncias alheias à vontade do agente, logo, tentativa (art. 14, II do CP).",
        "lesão corporal, pois houve desistência voluntária": "Nesse caso houve homicídio na forma tentada. Não há que se falar em desistência voluntária, uma vez que a desistência do agente se deu em razão de uma influência externa coativa (a chegada da polícia). Logo, Cássio não desistiu porque quis, mas porque se viu obrigado a isso. Assim, podemos dizer que foi iniciada a execução, mas a consumação não ocorreu por circunstâncias alheias à vontade do agente, logo, tentativa (art. 14, II do CP).",
        "tentativa de homicídio, com diminuição da pena pelo arrependimento eficaz": " Nesse caso houve homicídio na forma tentada. Não há que se falar em desistência voluntária, uma vez que a desistência do agente se deu em razão de uma influência externa coativa (a chegada da polícia). Logo, Cássio não desistiu porque quis, mas porque se viu obrigado a isso. Assim, podemos dizer que foi iniciada a execução, mas a consumação não ocorreu por circunstâncias alheias à vontade do agente, logo, tentativa (art. 14, II do CP). ",
        "lesão corporal, pois houve arrependimento eficaz": "Nesse caso houve homicídio na forma tentada. Não há que se falar em desistência voluntária, uma vez que a desistência do agente se deu em razão de uma influência externa coativa (a chegada da polícia). Logo, Cássio não desistiu porque quis, mas porque se viu obrigado a isso. Assim, podemos dizer que foi iniciada a execução, mas a consumação não ocorreu por circunstâncias alheias à vontade do agente, logo, tentativa (art. 14, II do CP).",
      },
    },

    {
      pergunta: "(FGV/2021/PCRN) Haroldo convence Bruna a aplicarem um golpe no casal de noivos Marcos e Fátima, apresentando-se como organizadores de casamento. Após receberem do casal vultosa quantia para a organização das bodas, Haroldo e Bruna mudaram de cidade e trocaram de telefone. Percebendo que haviam sido vítimas de um golpe, Marcos e Fátima registraram os fatos na delegacia, demonstrando interesse em ver os autores responsabilizados pelo crime de estelionato. Após o registro da ocorrência, Bruna, arrependida, por conta própria, efetuou a devolução ao casal de parte do dinheiro que havia recebido. Considerando que houve reparação parcial do dano: ",
      respostasErradas: ["a conduta de Haroldo e Bruna tornou-se atípica, tratando-se de mero ilícito civil", "Haroldo responderá por estelionato consumado, enquanto Bruna terá sua tipicidade afastada pela reparação parcial do dano", "Haroldo e Bruna responderão por estelionato, devendo Bruna ter sua pena diminuída pelo arrependimento posterior", "Haroldo responderá por estelionato tentado, enquanto Bruna terá sua tipicidade afastada pela reparação parcial do dano"],
      respostaCorreta: "Haroldo e Bruna responderão por estelionato, sem a causa de diminuição da pena pelo arrependimento posterior",
      mensagem: "[CORRETA]  O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. No caso em tela, a reparação não foi integral, motivo pelo qual não há que se falar no benefício (redução de pena de um a dois terços) do arrependimento posterior.",
      mensagensErradas: {
        "a conduta de Haroldo e Bruna tornou-se atípica, tratando-se de mero ilícito civil": " O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. No caso em tela, a reparação não foi integral, motivo pelo qual não há que se falar no benefício (redução de pena de um a dois terços) do arrependimento posterior.",
        "Haroldo responderá por estelionato consumado, enquanto Bruna terá sua tipicidade afastada pela reparação parcial do dano": "O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. No caso em tela, a reparação não foi integral, motivo pelo qual não há que se falar no benefício (redução de pena de um a dois terços) do arrependimento posterior.",
        "Haroldo e Bruna responderão por estelionato, devendo Bruna ter sua pena diminuída pelo arrependimento posterior": " O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. No caso em tela, a reparação não foi integral, motivo pelo qual não há que se falar no benefício (redução de pena de um a dois terços) do arrependimento posterior. ",
        "Haroldo responderá por estelionato tentado, enquanto Bruna terá sua tipicidade afastada pela reparação parcial do dano": "O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. No caso em tela, a reparação não foi integral, motivo pelo qual não há que se falar no benefício (redução de pena de um a dois terços) do arrependimento posterior.",
      },
    },

    {
      pergunta: "(FGV/2022/TJAP/JUIZ) Sobre os institutos da desistência voluntária, do arrependimento eficaz e do arrependimento posterior, é correto afirmar que: ",
      respostasErradas: ["a não consumação, por circunstâncias alheias à vontade do agente, é compatível com a desistência voluntária", "o reconhecimento da desistência voluntária dispensa o exame do iter criminis", "as circunstâncias inerentes à vontade do agente são irrelevantes para a configuração da desistência voluntária", "o reconhecimento da desistência voluntária dispensa o exame do elemento subjetivo da conduta"],
      respostaCorreta: "o arrependimento eficaz e a desistência voluntária somente são aplicáveis a delito que não tenha sido consumado",
      mensagem: "[CORRETA] Item correto, pois o arrependimento eficaz e a desistência voluntária somente são aplicáveis a delito que não tenha sido consumado. Uma vez consumado o delito, incabível qualquer destes dois institutos, nos termos do art. 15 do CP.",
      mensagensErradas: {
        "a não consumação, por circunstâncias alheias à vontade do agente, é compatível com a desistência voluntária": " Item errado, pois a não consumação, por circunstâncias alheias à vontade do agente, é incompatível com a desistência voluntária, na medida em que a desistência voluntária pressupõe que a consumação não ocorra pela vontade do agente.",
        "o reconhecimento da desistência voluntária dispensa o exame do iter criminis": "Item errado, pois o reconhecimento da desistência voluntária NÃO dispensa o exame do iter criminis, já que é indispensável que o agente já tenha iniciado a execução mas ainda não tenha finalizado os atos executórios.",
        "as circunstâncias inerentes à vontade do agente são irrelevantes para a configuração da desistência voluntária": " Item errado, pois as circunstâncias inerentes à vontade do agente são relevantes para a configuração da desistência voluntária, na medida em que a desistência voluntária pressupõe que a consumação não ocorra pela vontade do agente ",
        "o reconhecimento da desistência voluntária dispensa o exame do elemento subjetivo da conduta": "Item errado, pois o reconhecimento da desistência voluntária não dispensa o exame do elemento subjetivo da conduta. Para sabermos se o agente agiu com desistência voluntária, precisamos saber qual era seu intento final, a fim de delimitarmos a existência, ou não, da desistência voluntária.",
      },
    },

    {
      pergunta: "(FGV/2022/MPE-GO/PROMOTOR) A causa de diminuição do Art. 16 do Código Penal, referente ao arrependimento posterior, somente tem aplicação se houver: ",
      respostasErradas: ["a restituição da coisa antes do recebimento da denúncia, não possibilitada sua reparação, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima", "a restituição da coisa antes do recebimento da denúncia, não possibilitada sua reparação, variando o índice de redução da pena em função da integralidade e preservação do bem restituído", "a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da integralidade do bem restituído", "a restituição da coisa antes do oferecimento da denúncia, não possibilitada sua reparação, variando o índice de redução da pena em função da integralidade e preservação do bem restituído"],
      respostaCorreta: "a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima",
      mensagem: "[CORRETA] O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. Segundo a jurisprudência, a quantidade de redução de pena irá variar em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima: quanto mais célere, maior a redução: (...) No que tange à causa de diminuição do art. 16 do CP, é entendimento desta Corte que 'a causa de diminuição de pena relativa ao artigo 16 do Código Penal (arrependimento posterior) somente tem aplicação se houver a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima. Na espécie, não foi preenchido o requisito relativo à reparação integral do dano, eis que as instâncias de origem consignaram que houve apenas devolução parcial' (...) (STJ - AgRg nos EDcl no REsp 1710029/RN, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 08/06/2021, DJe 11/06/2021)",
      mensagensErradas: {
        "a restituição da coisa antes do recebimento da denúncia, não possibilitada sua reparação, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima": "O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. Segundo a jurisprudência, a quantidade de redução de pena irá variar em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima: quanto mais célere, maior a redução: (...) No que tange à causa de diminuição do art. 16 do CP, é entendimento desta Corte que 'a causa de diminuição de pena relativa ao artigo 16 do Código Penal (arrependimento posterior) somente tem aplicação se houver a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima. Na espécie, não foi preenchido o requisito relativo à reparação integral do dano, eis que as instâncias de origem consignaram que houve apenas devolução parcial' (...) (STJ - AgRg nos EDcl no REsp 1710029/RN, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 08/06/2021, DJe 11/06/2021)",
        "a restituição da coisa antes do recebimento da denúncia, não possibilitada sua reparação, variando o índice de redução da pena em função da integralidade e preservação do bem restituído": "O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. Segundo a jurisprudência, a quantidade de redução de pena irá variar em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima: quanto mais célere, maior a redução: (...) No que tange à causa de diminuição do art. 16 do CP, é entendimento desta Corte que 'a causa de diminuição de pena relativa ao artigo 16 do Código Penal (arrependimento posterior) somente tem aplicação se houver a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima. Na espécie, não foi preenchido o requisito relativo à reparação integral do dano, eis que as instâncias de origem consignaram que houve apenas devolução parcial' (...) (STJ - AgRg nos EDcl no REsp 1710029/RN, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 08/06/2021, DJe 11/06/2021)",
        "a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da integralidade do bem restituído": " O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. Segundo a jurisprudência, a quantidade de redução de pena irá variar em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima: quanto mais célere, maior a redução: (...) No que tange à causa de diminuição do art. 16 do CP, é entendimento desta Corte que 'a causa de diminuição de pena relativa ao artigo 16 do Código Penal (arrependimento posterior) somente tem aplicação se houver a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima. Na espécie, não foi preenchido o requisito relativo à reparação integral do dano, eis que as instâncias de origem consignaram que houve apenas devolução parcial' (...) (STJ - AgRg nos EDcl no REsp 1710029/RN, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 08/06/2021, DJe 11/06/2021)",
        "a restituição da coisa antes do oferecimento da denúncia, não possibilitada sua reparação, variando o índice de redução da pena em função da integralidade e preservação do bem restituído": "O arrependimento posterior está previsto no art. 16 do CP: Art. 16 - Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços. (Redação dada pela Lei nº 7.209, de 11.7.1984) Logo, é necessário que haja: a) reparação integral do dano ou restituição da coisa; b) voluntariedade; c) reparação/restituição antes do recebimento da ação penal; d) crime sem violência ou grave ameaça à pessoa. Segundo a jurisprudência, a quantidade de redução de pena irá variar em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima: quanto mais célere, maior a redução: (...) No que tange à causa de diminuição do art. 16 do CP, é entendimento desta Corte que 'a causa de diminuição de pena relativa ao artigo 16 do Código Penal (arrependimento posterior) somente tem aplicação se houver a integral reparação do dano ou a restituição da coisa antes do recebimento da denúncia, variando o índice de redução da pena em função da maior ou menor celeridade no ressarcimento do prejuízo à vítima. Na espécie, não foi preenchido o requisito relativo à reparação integral do dano, eis que as instâncias de origem consignaram que houve apenas devolução parcial' (...) (STJ - AgRg nos EDcl no REsp 1710029/RN, Rel. Ministro RIBEIRO DANTAS, QUINTA TURMA, julgado em 08/06/2021, DJe 11/06/2021)",
      },
    },

  ];

  return (
    <div>
      <Questionario perguntas={perguntas} />
    </div>
  );
};

export default Penal;
